from __future__ import annotations


def register_adjustment_applicability_parsers(sub) -> None:
    p = sub.add_parser("audit-historical-merger-spinoff-applicability-v321")
    p.add_argument("--terms-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/primary_adjustment_documents_phase587")
    p.add_argument("--trading-calendar-db", default="data/backup/stock_analytics_20260808_194044_baseline_v321.db")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/historical_merger_spinoff_not_applicable_evidence_phase590_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/historical_merger_spinoff_applicability_audit_phase590_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/historical_merger_spinoff_applicability_summary_phase590_v321.json")
    p = sub.add_parser("reparse-celltrion-merger-v321")
    p.add_argument("--applicability-audit-csv", default="data/raw/v321/events/historical_merger_spinoff_applicability_audit_phase590_v321.csv")
    p.add_argument("--terms-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--official-candidates-csv", default="data/raw/v321/events/official_candidates/official_event_candidates_v321.csv")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/celltrion_merger_not_applicable_evidence_phase591_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/celltrion_merger_reparse_audit_phase591_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/celltrion_merger_reparse_summary_phase591_v321.json")
    p = sub.add_parser("audit-historical-capital-reductions-v321")
    p.add_argument("--terms-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/primary_adjustment_documents_phase587")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/historical_capital_reduction_not_applicable_evidence_phase592_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/historical_capital_reduction_applicability_audit_phase592_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/historical_capital_reduction_applicability_summary_phase592_v321.json")
    p = sub.add_parser("audit-incomplete-primary-adjustments-v321")
    p.add_argument("--terms-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/primary_adjustment_documents_phase587")
    p.add_argument("--trading-calendar-db", default="data/backup/stock_analytics_20260808_194044_baseline_v321.db")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/incomplete_primary_not_applicable_evidence_phase593_v321.csv")
    p.add_argument("--review-output-csv", default="data/raw/v321/events/direct_primary_reparse_queue_phase593_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/incomplete_primary_applicability_audit_phase593_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/incomplete_primary_applicability_summary_phase593_v321.json")
