from __future__ import annotations


def register_cash_distribution_parsers(sub) -> None:
    p = sub.add_parser("build-stock-cash-amount-candidates-v321")
    p.add_argument("--dividend-facts-csv", required=True)
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_cash_amount_candidates_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/stock_cash_amount_candidates_audit.csv")
    p.add_argument("--etf-code", action="append", default=["069500"])
    p = sub.add_parser("prepare-official-cash-events-v321")
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/official_cash_events_v321.csv")
    p.add_argument("--etf-code", action="append", default=["069500"])
    p = sub.add_parser("validate-official-cash-events-v321")
    p.add_argument("--official-cash-events-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/cash_distribution_strict_evidence_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/cash_distribution_strict_evidence_audit.csv")
    p = sub.add_parser("compare-cash-amount-candidates-v321")
    p.add_argument("--strict-cash-evidence-csv", required=True)
    p.add_argument("--amount-candidates-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/cash_amount_crosscheck_audit.csv")
    p.add_argument("--tolerance", type=float, default=1e-9)
    p = sub.add_parser("prepare-benchmark-etf-distributions-v321")
    p.add_argument("--output-csv", default="data/raw/v321/events/benchmark_etf_distributions_069500.csv")
    p.add_argument("--code", default="069500")
    p = sub.add_parser("validate-benchmark-etf-distributions-v321")
    p.add_argument("--official-csv", required=True)
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/benchmark_etf_distribution_strict_evidence_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/benchmark_etf_distribution_audit.csv")
    p.add_argument("--code", default="069500")
    p = sub.add_parser("inject-benchmark-etf-events-v321")
    p.add_argument("--strict-evidence-csv", required=True)
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--queue-registry-csv", required=True)
    p.add_argument("--output-verification-csv", default="data/raw/v321/events/event_verification_with_benchmark_v321.csv")
    p.add_argument("--output-registry-csv", default="data/raw/v321/events/event_verification_with_benchmark_queue_registry.csv")
