from __future__ import annotations


def register_corporate_action_parsers(sub) -> None:
    p = sub.add_parser("audit-market-notice-coverage-v321")
    p.add_argument("--acquisition-manifest-csv", default="data/raw/v321/events/recent_dividend_acquisition_enriched_phase542_v321.csv")
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/official_event_evidence_strict_v321.csv")
    p.add_argument("--discovery-csv", action="append", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/market_notice_coverage_audit_phase542_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/market_notice_coverage_summary_phase542_v321.json")
    p = sub.add_parser("classify-recent-corporate-actions-v321")
    p.add_argument("--priority-queue-csv", default="data/raw/v321/events/event_resolution_priority_queue_phase542_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/recent_corporate_action_acquisition_queue_phase543_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/recent_corporate_action_summary_phase543_v321.json")
    p = sub.add_parser("build-corporate-action-candidate-manifest-v321")
    p.add_argument("--classified-queue-csv", default="data/raw/v321/events/recent_corporate_action_acquisition_queue_phase543_v321.csv")
    p.add_argument("--official-candidates-csv", default="data/raw/v321/events/official_candidates/official_event_candidates_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/corporate_action_candidate_manifest_phase544_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/corporate_action_candidate_summary_phase544_v321.json")
    p = sub.add_parser("select-market-adjustment-candidates-v321")
    p.add_argument("--candidate-manifest-csv", default="data/raw/v321/events/corporate_action_candidate_manifest_phase544_v321.csv")
    p.add_argument("--official-candidates-csv", default="data/raw/v321/events/official_candidates/official_event_candidates_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/market_adjustment_candidates_phase545_v321.csv")
    p = sub.add_parser("acquire-missing-corporate-action-documents-v321")
    p.add_argument("--candidate-manifest-csv", default="data/raw/v321/events/corporate_action_candidate_manifest_phase544_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/corporate_action_documents_phase546")
    p.add_argument("--output-csv", default="data/raw/v321/events/corporate_action_document_acquisition_phase546_v321.csv")
    p = sub.add_parser("parse-corporate-action-documents-v321")
    p.add_argument("--acquisition-csv", default="data/raw/v321/events/corporate_action_document_acquisition_phase546_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/corporate_action_document_parsed_phase547_v321.csv")
    p = sub.add_parser("review-complex-corporate-actions-v321")
    p.add_argument("--candidate-manifest-csv", default="data/raw/v321/events/corporate_action_candidate_manifest_phase544_v321.csv")
    p.add_argument("--official-candidates-csv", default="data/raw/v321/events/official_candidates/official_event_candidates_v321.csv")
    p.add_argument("--not-applicable-csv", default="data/raw/v321/events/corporate_action_not_applicable_phase548_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/complex_corporate_action_audit_phase548_v321.csv")
