from __future__ import annotations


def register_data_operation_parsers(sub) -> None:
    p = sub.add_parser("import-valuation-snapshots-v321")
    p.add_argument("--csv", required=True)
    p = sub.add_parser("build-data-foundation-v321")
    p.add_argument("--valuation-csv")
    p.add_argument("--total-return-csv")
    p.add_argument("--corporate-actions-csv")
    p.add_argument("--universe-history-csv")
    p.add_argument("--output-dir", default="data/v321_foundation")
    p = sub.add_parser("krx-provider-check-v321")
    p.add_argument("--code", default="005930")
    p.add_argument("--end", default="20260709")
    p = sub.add_parser("acquire-historical-data-v321")
    p.add_argument("--universe-csv", required=True)
    p.add_argument("--start", required=True)
    p.add_argument("--end", default="20260709")
    p.add_argument("--frequency", choices=["d", "m"], default="m")
    p.add_argument("--index-code")
    p.add_argument("--sleep-seconds", type=float, default=.15)
    p.add_argument("--output-dir", default="data/raw/v321")
    p.add_argument("--timeout-seconds", type=float, default=45.0)
    p.add_argument("--max-retries", type=int, default=3)
    p.add_argument("--retry-backoff-seconds", type=float, default=2.0)
    p.add_argument("--no-resume", action="store_true")
    p = sub.add_parser("db-health-v321")
    p.add_argument("--benchmark-code", default="069500")
    p.add_argument("--output-json")
    p = sub.add_parser("backup-db-v321")
    p.add_argument("--output-dir", default="data/backup")
    p.add_argument("--label", default="manual")
