from __future__ import annotations


def register_direct_action_parsers(sub) -> None:
    p = sub.add_parser("build-direct-action-document-inventory-v321")
    p.add_argument("--priority-queue-csv", default="data/raw/v321/events/current_resolution_priority_phase560_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--prior-acquisition-csv", default="data/raw/v321/events/corporate_action_document_acquisition_phase546_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/direct_action_documents_phase561")
    p.add_argument("--output-csv", default="data/raw/v321/events/direct_action_document_inventory_phase561_v321.csv")
    p = sub.add_parser("review-direct-action-groups-v321")
    p.add_argument("--inventory-csv", default="data/raw/v321/events/direct_action_document_inventory_phase561_v321.csv")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/direct_action_not_applicable_phase562_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/direct_action_group_audit_phase562_v321.csv")
    p.add_argument("--parsed-documents-csv", default="data/raw/v321/events/corporate_action_document_parsed_phase547_v321.csv")
    p = sub.add_parser("integrate-direct-action-evidence-v321")
    p.add_argument("--verification-csv", default="data/raw/v321/events/event_verification_resolved_phase560_v321.csv")
    p.add_argument("--evidence-csv", default="data/raw/v321/events/direct_action_not_applicable_phase562_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_resolved_phase563_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/direct_action_integration_audit_phase563_v321.csv")
    p.add_argument("--priority-output-csv", default="data/raw/v321/events/current_resolution_priority_phase563_v321.csv")
    p.add_argument("--priority-summary-json", default="data/raw/v321/events/current_resolution_priority_summary_phase563_v321.json")
    p = sub.add_parser("verify-samsung-sdi-rights-v321")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/samsung_sdi_rights_strict_evidence_phase564_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/samsung_sdi_rights_audit_phase564_v321.csv")
    p = sub.add_parser("integrate-strict-event-evidence-v321")
    p.add_argument("--verification-csv", default="data/raw/v321/events/event_verification_resolved_phase563_v321.csv")
    p.add_argument("--evidence-csv", default="data/raw/v321/events/samsung_sdi_rights_strict_evidence_phase564_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_resolved_phase565_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/strict_evidence_integration_audit_phase565_v321.csv")
    p.add_argument("--priority-output-csv", default="data/raw/v321/events/current_resolution_priority_phase565_v321.csv")
    p.add_argument("--priority-summary-json", default="data/raw/v321/events/current_resolution_priority_summary_phase565_v321.json")
    p = sub.add_parser("route-actionable-resolution-backlog-v321")
    p.add_argument("--priority-queue-csv", default="data/raw/v321/events/current_resolution_priority_phase565_v321.csv")
    p.add_argument("--direct-action-audit-csv", default="data/raw/v321/events/direct_action_group_audit_phase562_v321.csv")
    p.add_argument("--complex-evidence-audit-csv", default="data/raw/v321/events/spinoff_evidence_completeness_phase552_v321.csv")
    p.add_argument("--actionable-output-csv", default="data/raw/v321/events/actionable_resolution_queue_phase566_v321.csv")
    p.add_argument("--blocked-output-csv", default="data/raw/v321/events/blocked_resolution_queue_phase566_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/actionable_resolution_summary_phase566_v321.json")
