from __future__ import annotations


def register_dividend_resolution_parsers(sub) -> None:
    p = sub.add_parser("resolve-ambiguous-kind-notice-v321")
    p.add_argument("--residual-csv", default="data/raw/v321/events/residual_dividend_backlog_phase574_v321.csv")
    p.add_argument("--parsed-decisions-csv", default="data/raw/v321/events/historical_dividend_decision_parsed_phase569_v321.csv")
    p.add_argument("--discovery-output-csv", default="data/raw/v321/events/ambiguous_kind_notice_resolved_phase575_v321.csv")
    p.add_argument("--candidate-audit-csv", default="data/raw/v321/events/ambiguous_kind_notice_candidates_audit_phase575_v321.csv")
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/ambiguous_kind_strict_evidence_phase575_v321.csv")
    p.add_argument("--strict-audit-csv", default="data/raw/v321/events/ambiguous_kind_strict_evidence_audit_phase575_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("resolve-broadened-kind-notices-v321")
    p.add_argument("--residual-csv", default="data/raw/v321/events/residual_dividend_backlog_phase576_v321.csv")
    p.add_argument("--prior-discovery-audit-csv", default="data/raw/v321/events/historical_kind_exdate_discovery_audit_phase571_v321.csv")
    p.add_argument("--candidates-csv", default="data/raw/v321/events/historical_dividend_exdate_candidates_phase570_v321.csv")
    p.add_argument("--parsed-decisions-csv", default="data/raw/v321/events/historical_dividend_decision_parsed_phase569_v321.csv")
    p.add_argument("--discovery-output-csv", default="data/raw/v321/events/broadened_kind_notice_resolved_phase577_v321.csv")
    p.add_argument("--candidate-audit-csv", default="data/raw/v321/events/broadened_kind_notice_candidates_audit_phase577_v321.csv")
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/broadened_kind_strict_evidence_phase577_v321.csv")
    p.add_argument("--strict-audit-csv", default="data/raw/v321/events/broadened_kind_strict_evidence_audit_phase577_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("recover-pre-exdate-dividend-evidence-v321")
    p.add_argument("--residual-csv", default="data/raw/v321/events/residual_dividend_backlog_phase577_v321.csv")
    p.add_argument("--parsed-decisions-csv", default="data/raw/v321/events/historical_dividend_decision_parsed_phase569_v321.csv")
    p.add_argument("--candidates-csv", default="data/raw/v321/events/historical_dividend_exdate_candidates_phase570_v321.csv")
    p.add_argument("--provenance-audit-csv", default="data/raw/v321/events/pre_exdate_provenance_audit_phase578_v321.csv")
    p.add_argument("--discovery-output-csv", default="data/raw/v321/events/pre_exdate_kind_notice_resolved_phase578_v321.csv")
    p.add_argument("--discovery-audit-csv", default="data/raw/v321/events/pre_exdate_kind_notice_audit_phase578_v321.csv")
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/pre_exdate_strict_evidence_phase578_v321.csv")
    p.add_argument("--strict-audit-csv", default="data/raw/v321/events/pre_exdate_strict_evidence_audit_phase578_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("resolve-explicit-no-dividend-v321")
    p.add_argument("--residual-csv", default="data/raw/v321/events/residual_dividend_backlog_phase578_v321.csv")
    p.add_argument("--dividend-facts-csv", default="data/raw/v321/events/dividend_disclosure_facts.csv")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/explicit_no_dividend_evidence_phase579_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/explicit_no_dividend_audit_phase579_v321.csv")
    p.add_argument("--business-year", default="2024")
