from __future__ import annotations


def register_event_reconciliation_parsers(sub) -> None:
    p = sub.add_parser("acquire-payout-actions-v321")
    p.add_argument("--universe-csv", required=True)
    p.add_argument("--start-year", type=int, default=2020)
    p.add_argument("--end-year", type=int, default=2026)
    p.add_argument("--output-dir", default="data/raw/v321/events")
    p.add_argument("--max-retries", type=int, default=3)
    p.add_argument("--retry-backoff-seconds", type=float, default=1.0)
    p.add_argument("--sleep-seconds", type=float, default=.05)
    p = sub.add_parser("build-event-reconciliation-v321")
    p.add_argument("--dividend-facts-csv", required=True)
    p.add_argument("--action-disclosures-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/event_reconciliation_queue.csv")
    p = sub.add_parser("build-total-return-v321")
    p.add_argument("--corporate-actions-csv", default="data/v321_foundation/corporate_actions_v321.csv")
    p.add_argument("--coverage-json", default="data/v321_foundation/total_return_coverage_guarded_phase553_v321.json")
    p.add_argument("--output-csv", default="data/v321_foundation/total_return_history_v321.csv")
    p.add_argument("--benchmark-code", default="069500")
    p = sub.add_parser("prepare-event-verification-v321")
    p.add_argument("--queue-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_v321.csv")
    p = sub.add_parser("finalize-event-reconciliation-v321")
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--queue-registry-csv", required=True)
    p.add_argument("--canonical-output-csv", default="data/v321_foundation/corporate_actions_v321.csv")
    p.add_argument("--audit-output-csv", default="data/v321_foundation/event_reconciliation_audit.csv")
    p.add_argument("--coverage-json", default="data/v321_foundation/total_return_coverage_v321.json")
    p.add_argument("--coverage-start", default="20200101")
    p.add_argument("--coverage-end", default="20260709")
