from __future__ import annotations


def register_historical_kind_parsers(sub) -> None:
    p = sub.add_parser("discover-historical-kind-exdates-v321")
    p.add_argument("--candidates-csv", default="data/raw/v321/events/historical_dividend_exdate_candidates_phase570_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/historical_kind_exdate_discovery_phase571_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/historical_kind_exdate_discovery_audit_phase571_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("build-historical-kind-strict-evidence-v321")
    p.add_argument("--discovery-csv", default="data/raw/v321/events/historical_kind_exdate_discovery_phase571_v321.csv")
    p.add_argument("--parsed-decisions-csv", default="data/raw/v321/events/historical_dividend_decision_parsed_phase569_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/historical_kind_strict_evidence_phase572_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/historical_kind_strict_evidence_audit_phase572_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("integrate-historical-dividend-evidence-v321")
    p.add_argument("--verification-csv", default="data/raw/v321/events/event_verification_resolved_phase565_v321.csv")
    p.add_argument("--strict-ledger-csv", default="data/raw/v321/events/historical_kind_strict_evidence_phase572_v321.csv")
    p.add_argument("--selected-evidence-csv", default="data/raw/v321/events/historical_dividend_selected_evidence_phase573_v321.csv")
    p.add_argument("--selection-audit-csv", default="data/raw/v321/events/historical_dividend_selection_audit_phase573_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_resolved_phase573_v321.csv")
    p.add_argument("--integration-audit-csv", default="data/raw/v321/events/historical_dividend_integration_audit_phase573_v321.csv")
    p.add_argument("--priority-output-csv", default="data/raw/v321/events/current_resolution_priority_phase573_v321.csv")
    p.add_argument("--priority-summary-json", default="data/raw/v321/events/current_resolution_priority_summary_phase573_v321.json")
    p = sub.add_parser("build-residual-dividend-backlog-v321")
    p.add_argument("--actionable-queue-csv", default="data/raw/v321/events/actionable_resolution_queue_phase574_v321.csv")
    p.add_argument("--acquisition-csv", default="data/raw/v321/events/historical_dividend_decision_acquisition_phase568_v321.csv")
    p.add_argument("--candidates-csv", default="data/raw/v321/events/historical_dividend_exdate_candidates_phase570_v321.csv")
    p.add_argument("--discovery-audit-csv", default="data/raw/v321/events/historical_kind_exdate_discovery_audit_phase571_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/residual_dividend_backlog_phase574_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/residual_dividend_backlog_summary_phase574_v321.json")
