from __future__ import annotations


def register_historical_chain_parsers(sub) -> None:
    p = sub.add_parser("quarantine-periodic-dividend-aggregates-v321")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--dividend-facts-csv", default="data/raw/v321/events/dividend_disclosure_facts.csv")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/periodic_dividend_aggregate_not_applicable_evidence_phase583_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/periodic_dividend_aggregate_quarantine_audit_phase583_v321.csv")
    p.add_argument("--replacement-queue-csv", default="data/raw/v321/events/discrete_dividend_reconstruction_queue_phase583_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/periodic_dividend_aggregate_quarantine_summary_phase583_v321.json")
    p = sub.add_parser("build-historical-legal-event-chain-v321")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/historical_legal_event_chain_phase584_v321.csv")
    p.add_argument("--review-queue-csv", default="data/raw/v321/events/historical_legal_event_chain_review_phase584_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/historical_legal_event_chain_summary_phase584_v321.json")
    p = sub.add_parser("validate-historical-chain-documents-v321")
    p.add_argument("--chain-csv", default="data/raw/v321/events/historical_legal_event_chain_phase584_v321.csv")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/historical_chain_documents_phase585")
    p.add_argument("--output-csv", default="data/raw/v321/events/historical_chain_document_validation_phase585_v321.csv")
    p.add_argument("--review-queue-csv", default="data/raw/v321/events/historical_chain_document_review_phase585_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/historical_chain_document_validation_summary_phase585_v321.json")
    p = sub.add_parser("consolidate-historical-legal-chains-v321")
    p.add_argument("--validation-csv", default="data/raw/v321/events/historical_chain_document_validation_phase585_v321.csv")
    p.add_argument("--chain-csv", default="data/raw/v321/events/historical_legal_event_chain_phase584_v321.csv")
    p.add_argument("--group-output-csv", default="data/raw/v321/events/historical_legal_event_groups_phase586_v321.csv")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/historical_chain_not_applicable_evidence_phase586_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/historical_chain_consolidation_audit_phase586_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/historical_chain_consolidation_summary_phase586_v321.json")
