from __future__ import annotations


def register_kind_followup_parsers(sub) -> None:
    p = sub.add_parser("extract-kind-aggregate-market-targets-v321")
    p.add_argument("--aggregate-manifest-csv", default="data/raw/v321/events/kind_aggregate_market_notice_manifest_phase538_v321.csv")
    p.add_argument("--acquisition-manifest-csv", default="data/raw/v321/events/recent_dividend_acquisition_enriched_phase536_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_aggregate_market_targets_phase538_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_aggregate_market_audit_phase538_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("recover-acquisition-company-names-v321")
    p.add_argument("--acquisition-manifest-csv", default="data/raw/v321/events/recent_dividend_acquisition_manifest_phase536_v321.csv")
    p.add_argument("--dividend-facts-csv", default="data/raw/v321/events/dividend_disclosure_facts.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/recent_dividend_acquisition_enriched_phase536_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/company_name_recovery_audit_phase536_v321.csv")
    p = sub.add_parser("acquire-direct-kind-dividend-decisions-v321")
    p.add_argument("--manifest-csv", default="data/raw/v321/events/kind_direct_decision_manifest_phase537_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/kind_documents_phase537")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_direct_decision_pairing_phase537_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("build-paired-kind-market-observations-v321")
    p.add_argument("--pairing-csv", default="data/raw/v321/events/kind_dividend_decision_pairing_phase534_v321.csv")
    p.add_argument("--parsed-decisions-csv", default="data/raw/v321/events/kind_dividend_decision_parsed_phase534_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_paired_market_observations_phase535_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_paired_market_observations_audit_phase535_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("acquire-paired-kind-dividend-decisions-v321")
    p.add_argument("--notices-csv", default="data/raw/v321/events/kind_batch_market_notices_phase533_v321.csv")
    p.add_argument("--decision-disclosures-csv", default="data/raw/v321/events/stock_dividend_decision_disclosures_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/kind_documents_phase534")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_dividend_decision_pairing_phase534_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("prioritize-resolution-gaps-v321")
    p.add_argument("--resolved-verification-csv", default="data/raw/v321/events/event_verification_resolved_phase530_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/event_resolution_priority_queue_phase531_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/event_resolution_priority_summary_phase531_v321.json")
    p = sub.add_parser("build-recent-dividend-acquisition-manifest-v321")
    p.add_argument("--priority-queue-csv", default="data/raw/v321/events/event_resolution_priority_queue_phase531_v321.csv")
    p.add_argument("--decision-disclosures-csv", default="data/raw/v321/events/stock_dividend_decision_disclosures_v321.csv")
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/official_event_evidence_strict_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/recent_dividend_acquisition_manifest_phase532_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/recent_dividend_acquisition_summary_phase532_v321.json")
    p = sub.add_parser("discover-kind-market-notices-batch-v321")
    p.add_argument("--acquisition-manifest-csv", default="data/raw/v321/events/recent_dividend_acquisition_manifest_phase532_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_batch_market_notices_phase533_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_batch_market_search_audit_phase533_v321.csv")
    p.add_argument("--search-start", default="20260101")
    p.add_argument("--search-end", default="20260709")
    p.add_argument("--timeout-seconds", type=int, default=20)
    p = sub.add_parser("discover-kind-market-exdates-v321")
    p.add_argument("--candidates-csv", default="data/raw/v321/events/kind_market_exdate_discovery_candidates_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_market_exdate_discovered_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_market_exdate_discovery_audit_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
