from __future__ import annotations


def register_kind_parsers(sub) -> None:
    p = sub.add_parser("crosscheck-kind-dividends-v321")
    p.add_argument("--market-exdate-queue-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_dividend_crosscheck_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_dividend_crosscheck_audit.csv")
    p.add_argument("--timeout-seconds", type=float, default=15.0)
    p = sub.add_parser("retry-kind-dividends-v321")
    p.add_argument("--crosscheck-csv", default="data/raw/v321/events/kind_dividend_crosscheck_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_dividend_fetch_audit_v321.csv")
    p.add_argument("--retry-queue-csv", default="data/raw/v321/events/kind_dividend_retry_queue_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_dividend_crosscheck_status_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/kind_documents")
    p.add_argument("--timeout-seconds", type=int, default=15)
    p.add_argument("--dry-run", action="store_true")
    p = sub.add_parser("parse-kind-dividends-v321")
    p.add_argument("--documents-dir", default="data/raw/v321/events/kind_documents")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_dividend_parsed_v321.csv")
    p = sub.add_parser("reconcile-kind-dividends-v321")
    p.add_argument("--market-queue-csv", default="data/raw/v321/events/stock_dividend_market_exdate_verification_queue_v321.csv")
    p.add_argument("--crosscheck-csv", default="data/raw/v321/events/kind_dividend_crosscheck_v321.csv")
    p.add_argument("--parsed-csv", default="data/raw/v321/events/kind_dividend_parsed_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_dividend_candidate_reconciliation_audit_v321.csv")
    p.add_argument("--official-facts-csv", default="data/raw/v321/events/kind_dividend_official_facts_v321.csv")
    p = sub.add_parser("acquire-kind-market-exdates-v321")
    p.add_argument("--manifest-csv", default="data/raw/v321/events/kind_market_exdate_source_manifest_v321.csv")
    p.add_argument("--official-facts-csv", default="data/raw/v321/events/kind_dividend_official_facts_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/kind_market_exdate_observations_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kind_market_exdate_acquisition_audit_v321.csv")
    p.add_argument("--timeout-seconds", type=int, default=20)
