from __future__ import annotations


def register_kodex_distribution_parsers(sub) -> None:
    p = sub.add_parser("summarize-stock-dividend-resolution-v321")
    p.add_argument("--amount-candidates-csv", required=True)
    p.add_argument("--amount-audit-csv", required=True)
    p.add_argument("--output-json", default="data/raw/v321/events/stock_dividend_resolution_summary_v321.json")
    p = sub.add_parser("acquire-kodex-distributions-v321")
    p.add_argument("--output-dir", default="data/raw/v321/events/kodex_069500")
    p.add_argument("--url", default="https://m.samsungfund.com/etf/product/view.do?id=2ETF01")
    p.add_argument("--timeout-seconds", type=float, default=30.0)
    p = sub.add_parser("build-stock-dividend-ambiguity-report-v321")
    p.add_argument("--amount-audit-csv", required=True)
    p.add_argument("--amount-candidates-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_ambiguity_report_v321.csv")
    p = sub.add_parser("discover-kodex-dynamic-endpoints-v321")
    p.add_argument("--product-url", default="https://m.samsungfund.com/etf/product/view.do?id=2ETF01")
    p.add_argument("--output-dir", default="data/raw/v321/events/kodex_069500/dynamic")
    p.add_argument("--timeout-seconds", type=float, default=30.0)
    p.add_argument("--max-scripts", type=int, default=40)
    p = sub.add_parser("refine-stock-dividend-candidates-v321")
    p.add_argument("--dividend-facts-csv", required=True)
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_cash_amount_candidates_refined_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/stock_cash_amount_candidates_refined_audit.csv")
    p.add_argument("--etf-code", action="append", default=["069500"])
    p = sub.add_parser("rank-probe-kodex-endpoints-v321")
    p.add_argument("--candidate-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/kodex_069500/dynamic/kodex_endpoint_probe_v321.csv")
    p.add_argument("--top-n", type=int, default=25)
    p.add_argument("--timeout-seconds", type=float, default=12.0)
    p.add_argument("--product-host", default="m.samsungfund.com")
