from __future__ import annotations


def register_ml_parsers(sub) -> None:
    p = sub.add_parser("ml-readiness")
    p.add_argument("codes", nargs="*")
    p.add_argument("--universe-csv")
    p.add_argument("--portfolio-id", default="shadow_24_filtered")
    p = sub.add_parser("build-feature-store")
    p.add_argument("codes", nargs="*")
    p.add_argument("--universe-csv")
    p.add_argument("--benchmark-code", default="069500")
    p.add_argument("--industry", action="append", default=[])
    p = sub.add_parser("ml-train")
    p.add_argument("--horizon", type=int, choices=[5, 20, 60], default=20)
    p.add_argument("--benchmark-code", default="069500")
    p.add_argument("--validation-days", type=int, default=126)
    p.add_argument("--test-days", type=int, default=126)
    p.add_argument("--artifact", default="models/baseline_h20.joblib")
    p.add_argument("--output-prefix", default="ml_baseline")
    p = sub.add_parser("ml-walk-forward")
    p.add_argument("--horizon", type=int, choices=[5, 20, 60], default=20)
    p.add_argument("--benchmark-code", default="069500")
    p.add_argument("--min-train-days", type=int, default=504)
    p.add_argument("--test-days", type=int, default=126)
    p.add_argument("--output-csv", default="ml_walk_forward.csv")
    p = sub.add_parser("ml-predict")
    p.add_argument("--artifact", default="models/baseline_h20.joblib")
    p.add_argument("--output-csv", default="ml_latest_predictions.csv")
