from __future__ import annotations


def register_official_event_parsers(sub) -> None:
    p = sub.add_parser("prepare-official-event-evidence-v321")
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/official_event_evidence_v321.csv")
    p = sub.add_parser("resolve-official-events-v321")
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--evidence-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_resolved_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/official_event_resolution_audit.csv")
    p.add_argument("--not-applicable-csv")
    p.add_argument("--date-window-days", type=int, default=370)
    p = sub.add_parser("acquire-official-event-candidates-v321")
    p.add_argument("--universe-csv", required=True)
    p.add_argument("--start", default="20200101")
    p.add_argument("--end", default="20260709")
    p.add_argument("--output-dir", default="data/raw/v321/events/official_candidates")
    p.add_argument("--max-retries", type=int, default=3)
    p.add_argument("--retry-backoff-seconds", type=float, default=1.0)
    p.add_argument("--sleep-seconds", type=float, default=.05)
    p = sub.add_parser("enrich-official-evidence-v321")
    p.add_argument("--evidence-template-csv", required=True)
    p.add_argument("--candidate-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/official_event_evidence_enriched_v321.csv")
    p = sub.add_parser("build-market-adjustment-evidence-v321")
    p.add_argument("--official-candidates-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/market_adjustment_evidence_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/market_adjustment_evidence_audit.csv")
    p.add_argument("--window-days", type=int, default=20)
    p.add_argument("--max-match-distance-days", type=int, default=10)
    p.add_argument("--ratio-tolerance", type=float, default=.002)
    p = sub.add_parser("merge-strict-evidence-v321")
    p.add_argument("--evidence-csv", action="append", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/official_event_evidence_strict_v321.csv")
