from __future__ import annotations


def register_primary_adjustment_parsers(sub) -> None:
    p = sub.add_parser("extract-primary-adjustment-document-terms-v321")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--legal-groups-csv", default="data/raw/v321/events/historical_legal_event_groups_phase586_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/primary_adjustment_documents_phase587")
    p.add_argument("--output-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--review-queue-csv", default="data/raw/v321/events/primary_adjustment_document_review_phase587_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/primary_adjustment_document_terms_summary_phase587_v321.json")
    p = sub.add_parser("validate-primary-adjustment-market-dates-v321")
    p.add_argument("--terms-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--trading-calendar-db", default="data/backup/stock_analytics_20260808_194044_baseline_v321.db")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/primary_adjustment_market_evidence_phase588_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/primary_adjustment_market_validation_audit_phase588_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/primary_adjustment_market_validation_summary_phase588_v321.json")
    p = sub.add_parser("audit-historical-rights-applicability-v321")
    p.add_argument("--terms-csv", default="data/raw/v321/events/primary_adjustment_document_terms_phase587_v321.csv")
    p.add_argument("--execution-manifest-csv", default="data/raw/v321/events/historical_backlog_execution_manifest_phase582_v321.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/primary_adjustment_documents_phase587")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/historical_rights_not_applicable_evidence_phase589_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/historical_rights_applicability_audit_phase589_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/historical_rights_applicability_summary_phase589_v321.json")
