from __future__ import annotations


def register_stock_dividend_evidence_parsers(sub) -> None:
    p = sub.add_parser("acquire-stock-dividend-decisions-v321")
    p.add_argument("--universe-csv", required=True)
    p.add_argument("--start", default="20200101")
    p.add_argument("--end", default="20260709")
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_decision_disclosures_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/stock_dividend_decision_disclosures_audit.csv")
    p.add_argument("--sleep-seconds", type=float, default=.05)
    p = sub.add_parser("build-stock-dividend-exdate-queue-v321")
    p.add_argument("--refined-amount-candidates-csv", required=True)
    p.add_argument("--dividend-decisions-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_exdate_resolution_queue_v321.csv")
    p.add_argument("--match-days", type=int, default=430)
    p = sub.add_parser("inspect-kodex-high-signal-responses-v321")
    p.add_argument("--probe-csv", required=True)
    p.add_argument("--output-dir", default="data/raw/v321/events/kodex_069500/high_signal")
    p.add_argument("--min-response-keyword-score", type=int, default=2)
    p.add_argument("--timeout-seconds", type=float, default=15.0)
    p.add_argument("--product-host", default="m.samsungfund.com")
    p = sub.add_parser("extract-dart-dividend-record-dates-v321")
    p.add_argument("--decision-disclosures-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_official_date_candidates_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/stock_dividend_official_date_candidates_audit.csv")
    p.add_argument("--sleep-seconds", type=float, default=.05)
    p = sub.add_parser("merge-dividend-date-candidates-v321")
    p.add_argument("--exdate-queue-csv", required=True)
    p.add_argument("--dart-record-candidates-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_date_resolution_v321.csv")
    p.add_argument("--match-days", type=int, default=430)
    p = sub.add_parser("build-explicit-stock-exdate-evidence-v321")
    p.add_argument("--stock-dividend-date-resolution-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_explicit_exdate_strict_evidence_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/stock_dividend_explicit_exdate_audit.csv")
    p = sub.add_parser("export-benchmark-calendar-v321")
    p.add_argument("--benchmark-code", default="069500")
    p.add_argument("--output-csv", default="data/raw/v321/events/benchmark_069500_trading_calendar.csv")
    p.add_argument("--include-post-cutoff", action="store_true")
    p = sub.add_parser("build-record-date-calendar-candidates-v321")
    p.add_argument("--stock-dividend-date-resolution-csv", required=True)
    p.add_argument("--benchmark-prices-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_record_date_calendar_candidates_v321.csv")
    p = sub.add_parser("parse-kodex-distribution-tables-v321")
    p.add_argument("--bodies-dir", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/kodex_069500/high_signal/kodex_distribution_table_candidates_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/kodex_069500/high_signal/kodex_distribution_table_audit.csv")
    p = sub.add_parser("build-market-exdate-verification-queue-v321")
    p.add_argument("--stock-dividend-date-resolution-csv", required=True)
    p.add_argument("--record-date-calendar-candidates-csv", required=True)
    p.add_argument("--output-csv", default="data/raw/v321/events/stock_dividend_market_exdate_verification_queue_v321.csv")
    p = sub.add_parser("validate-official-market-exdates-v321")
    p.add_argument("--verification-csv", required=True)
    p.add_argument("--strict-evidence-csv", default="data/raw/v321/events/stock_dividend_market_exdate_strict_evidence_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/stock_dividend_market_exdate_strict_audit.csv")
    p = sub.add_parser("summarize-kodex-high-signal-bodies-v321")
    p.add_argument("--response-audit-csv", required=True)
    p.add_argument("--field-candidates-csv", required=True)
    p.add_argument("--output-json", default="data/raw/v321/events/kodex_069500/high_signal/kodex_high_signal_summary_v321.json")
