from __future__ import annotations


def register_subsidiary_action_parsers(sub) -> None:
    p = sub.add_parser("prioritize-current-resolution-backlog-v321")
    p.add_argument("--resolved-verification-csv", default="data/raw/v321/events/event_verification_resolved_phase548_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/current_resolution_priority_phase555_v321.csv")
    p.add_argument("--summary-json", default="data/raw/v321/events/current_resolution_priority_summary_phase555_v321.json")
    p = sub.add_parser("acquire-subsidiary-action-documents-v321")
    p.add_argument("--priority-queue-csv", default="data/raw/v321/events/current_resolution_priority_phase555_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/subsidiary_action_documents_phase556")
    p.add_argument("--output-csv", default="data/raw/v321/events/subsidiary_action_document_acquisition_phase556_v321.csv")
    p = sub.add_parser("parse-subsidiary-action-applicability-v321")
    p.add_argument("--acquisition-manifest-csv", default="data/raw/v321/events/subsidiary_action_document_acquisition_phase556_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/subsidiary_action_applicability_audit_phase557_v321.csv")
    p.add_argument("--not-applicable-output-csv", default="data/raw/v321/events/subsidiary_action_not_applicable_phase557_v321.csv")
    p = sub.add_parser("integrate-not-applicable-evidence-v321")
    p.add_argument("--verification-csv", default="data/raw/v321/events/event_verification_resolved_phase548_v321.csv")
    p.add_argument("--evidence-csv", default="data/raw/v321/events/subsidiary_action_not_applicable_phase557_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_resolved_phase558_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/not_applicable_integration_audit_phase558_v321.csv")
    p.add_argument("--priority-output-csv", default="data/raw/v321/events/current_resolution_priority_phase558_v321.csv")
    p.add_argument("--priority-summary-json", default="data/raw/v321/events/current_resolution_priority_summary_phase558_v321.json")
    p = sub.add_parser("resolve-residual-subsidiary-actions-v321")
    p.add_argument("--applicability-audit-csv", default="data/raw/v321/events/subsidiary_action_applicability_audit_phase557_v321.csv")
    p.add_argument("--acquisition-manifest-csv", default="data/raw/v321/events/subsidiary_action_document_acquisition_phase556_v321.csv")
    p.add_argument("--disclosures-csv", default="data/raw/v321/events/corporate_action_disclosures.csv")
    p.add_argument("--documents-dir", default="data/raw/v321/events/residual_subsidiary_documents_phase559")
    p.add_argument("--evidence-output-csv", default="data/raw/v321/events/residual_subsidiary_not_applicable_phase559_v321.csv")
    p.add_argument("--audit-output-csv", default="data/raw/v321/events/residual_subsidiary_audit_phase559_v321.csv")
    p = sub.add_parser("integrate-residual-subsidiary-evidence-v321")
    p.add_argument("--verification-csv", default="data/raw/v321/events/event_verification_resolved_phase558_v321.csv")
    p.add_argument("--evidence-csv", default="data/raw/v321/events/residual_subsidiary_not_applicable_phase559_v321.csv")
    p.add_argument("--output-csv", default="data/raw/v321/events/event_verification_resolved_phase560_v321.csv")
    p.add_argument("--audit-csv", default="data/raw/v321/events/residual_subsidiary_integration_audit_phase560_v321.csv")
    p.add_argument("--priority-output-csv", default="data/raw/v321/events/current_resolution_priority_phase560_v321.csv")
    p.add_argument("--priority-summary-json", default="data/raw/v321/events/current_resolution_priority_summary_phase560_v321.json")
